#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
TOTAL_MINUTES=12

# Nothing here is written to disk. The Docker Hub token is a publishing
# credential; it goes straight to GitHub Actions secrets and nowhere else, so
# this wizard deliberately never calls write_env.
GH_TARGET_REPO="frankieramirez/comicarr"
DOCKERHUB_NAMESPACE="comicarr"
DOCKERHUB_REPOSITORY="comicarr/comicarr"

banner "Docker Hub publishing setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight" 1
say "Release builds push to two registries. GHCR already works; this wizard"
say "sets up the Docker Hub mirror at ${DOCKERHUB_REPOSITORY}."
printf '\n'

if ! command -v gh >/dev/null 2>&1; then
  warn "the GitHub CLI (gh) is not installed — the wizard can still walk you"
  note "through Docker Hub, but you'll have to add the two secrets by hand."
elif ! gh auth status >/dev/null 2>&1; then
  warn "gh is installed but not authenticated. Run: gh auth login"
else
  export GH_REPO="$GH_TARGET_REPO"   # pin secret writes regardless of cwd
  say "GitHub CLI ready — secrets will be written to ${BOLD}${GH_TARGET_REPO}${RESET}."
fi

printf '\n'
note "You need a Docker Hub account named '${DOCKERHUB_NAMESPACE}'. A Docker Hub"
note "account owns the namespace matching its username, and Docker Personal"
note "(free) includes unlimited public repositories. An *organization* named"
note "'${DOCKERHUB_NAMESPACE}' would give the same namespace but requires a paid"
note "Team plan — only worth it if several people need push rights."
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the Docker Hub account" 4
say "Sign up for the account that will own the ${DOCKERHUB_NAMESPACE}/ namespace."
printf '\n'
step "If you're signed in as a different account, sign out first — the"
note "  username you register here becomes the image namespace permanently."
step "Register with the username: ${BOLD}${DOCKERHUB_NAMESPACE}${RESET}"
note "  Use an address you control that isn't already on Docker Hub;"
note "  a plus-alias such as you+comicarr@example.com works."
step "Verify the confirmation email, then sign in."
printf '\n'
open_url "https://app.docker.com/signup"
pause "Press Enter once you're signed in as '${DOCKERHUB_NAMESPACE}'"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Create the public repository" 3
say "Create ${DOCKERHUB_REPOSITORY} explicitly, before the first push."
printf '\n'
warn "Create it as Public. A private image is precisely the failure this"
note "  work is fixing (#545) — anonymous pulls of a private repo return 404,"
note "  and repositories cannot be renamed after creation."
printf '\n'
step "My Hub > Repositories > Create repository"
step "Namespace: ${BOLD}${DOCKERHUB_NAMESPACE}${RESET}   Name: ${BOLD}${DOCKERHUB_NAMESPACE}${RESET}"
step "Short description: An automated comic book library manager"
step "Visibility: ${BOLD}Public${RESET}"
printf '\n'
open_url "https://hub.docker.com/repository/create"
pause "Press Enter once the repository exists"

printf '\n'
repo_json=$(curl -fsS "https://hub.docker.com/v2/repositories/${DOCKERHUB_REPOSITORY}/" 2>/dev/null || true)
if [[ -z "$repo_json" ]]; then
  warn "couldn't see ${DOCKERHUB_REPOSITORY} yet — if you just created it, that's"
  note "  usually propagation. Re-run this wizard later to re-check."
elif printf '%s' "$repo_json" | grep -q '"is_private":[[:space:]]*true'; then
  warn "${DOCKERHUB_REPOSITORY} exists but is PRIVATE."
  note "  Fix it under Repository > Settings > Visibility before releasing,"
  note "  or anonymous 'docker pull' will 404."
  confirm "Continue anyway?" || exit 1
else
  printf '  %s✓%s %s is public\n' "$GREEN" "$RESET" "$DOCKERHUB_REPOSITORY"
fi
pause "Press Enter to continue"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Generate an access token" 2
say "CI authenticates with a personal access token, never your password."
printf '\n'
step "Avatar (top right) > Account settings > Personal access tokens"
step "Generate new token"
step "Description: ${BOLD}github-actions-release${RESET}"
step "Expiration: your call — put a calendar reminder to rotate it"
step "Access permissions: ${BOLD}Read, Write, Delete${RESET}"
note "  Delete is required: the release workflow also syncs the Docker Hub"
note "  page description, and that API rejects read/write-only tokens."
printf '\n'
warn "The token is shown exactly once. Copy it before closing the dialog."
printf '\n'
open_url "https://app.docker.com/settings/personal-access-tokens"
ask DOCKERHUB_USERNAME "Docker Hub username [${DOCKERHUB_NAMESPACE}]:"
[[ -z "$DOCKERHUB_USERNAME" ]] && DOCKERHUB_USERNAME="$DOCKERHUB_NAMESPACE"
ask_secret DOCKERHUB_TOKEN "Paste the access token:"

if [[ -z "$DOCKERHUB_TOKEN" ]]; then
  warn "no token entered — cannot continue."
  SKIPPED+=("Docker Hub token and both GitHub secrets")
  finish
  exit 1
fi

printf '\n'
if command -v docker >/dev/null 2>&1; then
  if printf '%s' "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin >/dev/null 2>&1; then
    printf '  %s✓%s token authenticates as %s\n' "$GREEN" "$RESET" "$DOCKERHUB_USERNAME"
    docker logout >/dev/null 2>&1 || true
  else
    warn "docker login failed with that username/token pair."
    confirm "Store it anyway?" || exit 1
  fi
else
  auth_code=$(curl -s -o /dev/null -w '%{http_code}' \
    -H "Content-Type: application/json" \
    -d "{\"username\":\"${DOCKERHUB_USERNAME}\",\"password\":\"${DOCKERHUB_TOKEN}\"}" \
    "https://hub.docker.com/v2/auth/token" 2>/dev/null || echo "000")
  if [[ "$auth_code" == "200" ]]; then
    printf '  %s✓%s token authenticates as %s\n' "$GREEN" "$RESET" "$DOCKERHUB_USERNAME"
  else
    warn "could not verify the token (HTTP ${auth_code})."
    confirm "Store it anyway?" || exit 1
  fi
fi
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Write the GitHub Actions secrets" 2
say "These two names are what .github/workflows/release.yml reads. Until both"
say "exist the release still succeeds — it just publishes to GHCR only."
printf '\n'
set_secret DOCKERHUB_USERNAME "$DOCKERHUB_USERNAME"
set_secret DOCKERHUB_TOKEN "$DOCKERHUB_TOKEN"
printf '\n'

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  # \b is a GNU extension; [[:space:]] keeps this working on BSD grep too.
  present=$(gh secret list --repo "$GH_TARGET_REPO" 2>/dev/null | grep -cE '^DOCKERHUB_(USERNAME|TOKEN)[[:space:]]' || true)
  if [[ "${present:-0}" -eq 2 ]]; then
    printf '  %s✓%s both secrets are present on %s\n' "$GREEN" "$RESET" "$GH_TARGET_REPO"
  else
    warn "expected 2 DOCKERHUB_* secrets on ${GH_TARGET_REPO}, found ${present:-0}."
  fi
fi

printf '\n'
note "Next release publishes to both registries. To mirror the current release"
note "without waiting, re-run the Release workflow from the Actions tab."
pause "Press Enter for the summary"

finish
